spring:
  thymeleaf:
    cache: false
    mode: HTML
  main.banner-mode: 'off'
  datasource.url: jdbc:h2:./db;AUTO_SERVER=TRUE
  h2.console.enabled: true

liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml

mybatis.type-handlers-package: io.github.hwestphal.mybatis

resources:
  cache: false
  version: '@git.commit.id.abbrev@'
